const prefix = 'https://billafy.pythonanywhere.com/chat-api/';

export const urls = {
	accountList: prefix+'account-list/',
	accountSearch: prefix+'account-search/',
	accountDetailed: prefix+'account-detailed/',
	accountCreate: prefix+'account-create/',
	accountUpdate: prefix+'account-update/',
	accountDelete: prefix+'account-delete/',
	accountLogin: prefix+'account-login/',
	passwordUpdate: prefix+'password-update/',
	validateEmail: prefix+'validate-email/',
	getFriendRequestsSent: prefix+'get-friend-requests-sent/',
	getFriendRequestsReceived: prefix+'get-friend-requests-received/',
	sendFriendRequest: prefix+'send-friend-request/',
	removeFriendRequest: prefix+'remove-friend-request/',
	acceptFriendRequest: prefix+'accept-friend-request/',
	getFriends: prefix+'get-friends/',
	removeFriend: prefix+'remove-friend/',
	getMessages: prefix+'get-messages/',
	getConversation: prefix+'get-conversation/',
	sendMessage: prefix+'send-message/',
	editMessage: prefix+'edit-message/',
	deletedMessage: prefix+'delete-message/',
};