# Generated by Django 3.1.7 on 2021-03-13 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatapi', '0009_auto_20210313_2251'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='id',
        ),
        migrations.AlterField(
            model_name='account',
            name='username',
            field=models.CharField(max_length=32, primary_key=True, serialize=False, unique=True),
        ),
    ]
