# Generated by Django 3.1.7 on 2021-03-13 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatapi', '0010_auto_20210313_2257'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='password',
        ),
    ]
