# Generated by Django 3.1.7 on 2021-03-14 17:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('chatapi', '0011_remove_account_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='accountCreated',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='account',
            name='dateOfBirth',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='account',
            name='email',
            field=models.EmailField(default='sample@gmail.com', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='account',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], default='M', max_length=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='account',
            name='isOnline',
            field=models.BooleanField(default=False),
        ),
    ]
