# Generated by Django 3.1.7 on 2021-03-18 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatapi', '0013_auto_20210318_2232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversation',
            name='lastMessaged',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
