# Generated by Django 3.1.7 on 2021-03-19 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatapi', '0016_auto_20210319_1006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friendrequest',
            name='receiver',
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name='friendrequest',
            name='sender',
            field=models.CharField(max_length=32),
        ),
    ]
