# Generated by Django 3.1.7 on 2021-03-19 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatapi', '0017_auto_20210319_1010'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Conversation',
            new_name='Friendship',
        ),
        migrations.RenameField(
            model_name='message',
            old_name='conversationId',
            new_name='friendshipId',
        ),
    ]
