# Generated by Django 3.1.7 on 2021-03-19 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatapi', '0019_message_read'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='friendshipId',
            field=models.IntegerField(),
        ),
    ]
